"""Generate summary TypeScript types from the actual JSON response schema."""

import argparse
import json
from pathlib import Path

from expense_tracker.summary_service import SummaryResponse


def type_name(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "anyOf" in schema:
        return " | ".join(type_name(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if schema.get("type") == "array":
        return f"Array<{type_name(schema['items'])}>"
    return {"string": "string", "number": "number", "integer": "number", "boolean": "boolean", "null": "null"}[
        schema["type"]
    ]


def generate() -> str:
    schema = SummaryResponse.model_json_schema(mode="serialization")
    models = {**schema.get("$defs", {}), "SummaryResponse": schema}
    lines = ["// Generated by scripts/generate_contracts.py. Do not edit by hand."]
    for name, model in models.items():
        lines.append(f"export interface {name} {{")
        for field, description in model["properties"].items():
            lines.append(f"  {field}: {type_name(description)};")
        lines.append("}\n")
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / "frontend/src/generated/summary.ts"
    expected = generate()
    if args.check:
        if not target.exists() or target.read_text() != expected:
            raise SystemExit("Regenerate contracts: uv run python scripts/generate_contracts.py")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected)
